### ISSUE TITLE
Merging duplicated years

### ISSUE THREAD

**Issue by Odhiambo1** [thedependentvariable/World_Bank_Boost_Prog-Kenya#1]
The periods  2014-15 and 2015-16 in the Year column exist with two variants such that doing getting unique  observations gives the result below:
> unique(kenya_boost$Year)
[1] 2016-17   2017-18   2013-14   2014-15  
[5] 2015-16    2015-16   2014-15 

I have tried to do gsub() to get and replace them with a uniform format but it's taking crazily long to run and freezes my laptop. 
@chrisorwa kindly help.

**Comment by chrisorwa** [comment]
This is quite odd, I suppose there is spacing that makes the years appear in two variants. 
Remove any space between the characters for both variants and check if they merge into one.

**Comment by Odhiambo1** [comment]
Removing the spaces worked.
Thanks a lot
